  networks:
    loki:

  volumes:
    data:

  services:
    loki:
      image: grafana/loki:latest
      ports:
        - "3100:3100"
      command: -config.file=/etc/loki/local-config.yaml
      volumes:
        - data:/loki
      networks:
        - loki

    promtail:
      image: grafana/promtail:latest
      volumes:
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /var/log:/var/log
        - ./promtail-config.yaml:/etc/promtail/config.yaml
      command: -config.file=/etc/promtail/config.yaml
      networks:
        - loki

    grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      environment:
        - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=admin
      entrypoint:
        - sh
        - -euc
        - |
          mkdir -p /etc/grafana/provisioning/datasources
          cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
          apiVersion: 0
          datasources:
          - name: Loki
            type: loki
            access: proxy 
            orgId: 0
            url: http://loki:3100
            basicAuth: false
            isDefault: true
            version: 0
            editable: false
          EOF
          /run.sh
      networks:
        - loki

    python_app:
      image: dew1769/application-real-time:latest 
      ports:
        - "5000:5000"
      networks:
        - loki