- name: Setup Docker Environment and Deploy Application
  hosts: all
  become: true

  tasks:
    - name: Setup Docker Environment
      block:
        - name: Install Docker
          apt:
            name: docker.io
            state: present

        - name: Start Docker Service
          service:
            name: docker
            state: started
            enabled: yes
      tags: 
        - setup

  roles:
    - web_app

  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_ed25519.pub"