- name: Install Docker Compose
  get_url:
    url:  https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: '0755'