name: Python Test

on: [push]

jobs:
    security:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-python@v4
              with:
                python-version: '3.9'
            - name: Install Dependencies
              run: pip install -r app_python/requirements.txt
            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/python@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set Up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'

            - name: Restore Cached Dependencies
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('app_python/requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-

            - name: Install Dependencies
              run: pip install -r app_python/requirements.txt

            - name: Lint Code
              run: |
                flake8 app_python

            - name: Run Unit Tests
              run: pytest app_python/test_cases.py

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set Up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                context: ./app_python
                file: ./app_python/Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/application-real-time:latest